# Site settings
title: Green Minds
email: sara@greenminds.se
description: > # this means to ignore newlines until "baseurl:"
Green Minds: Med passion för trädgård.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


paginate: 4
paginate_path: "blog/page:num"
